version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run: 
          name: "echo an env var that is part of our project"
          command: |
            echo $SONAR_TOKEN # this env var must be set within the project
      - cit/sonarcloud-scan

orbs:
  cit: chime/ci-tools@dev:6c46477

workflows:
  main:
    jobs:
      - build

